apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
  selector:
    io.kompose.service: elasticsearch
