apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out ./k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-deposit-secrets
                  key: ES_PASSWORD
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "true"
          image: elastic/elasticsearch:7.17.10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  curl -u elastic:$ELASTIC_PASSWORD -k http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  curl -u elastic:$ELASTIC_PASSWORD -k http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          name: user-deposit-es
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
