apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out ./k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: user-deposit-app
  name: user-deposit-app
spec:
  type: LoadBalancer
  ports:
    - name: user-deposit-app
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: user-deposit-app
